apiVersion: v1
kind: Service
metadata:
  name: {{ include "koptimize.fullname" . }}
  labels:
    {{- include "koptimize.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 8080
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "koptimize.selectorLabels" . | nindent 4 }}
