---
apiVersion: v2
name: netbird
description: NetBird VPN management platform
type: application
version: 0.12.1
appVersion: "0.21.7"
icon: https://avatars.githubusercontent.com/u/100464677
annotations:
  artifacthub.io/category: networking
  artifacthub.io/license: MIT
  artifacthub.io/prerelease: "true"
